services:
#    walva_haf.example.class: Walva\HafBundle\Example
   walva_haf.locale_listener:
        class: Walva\HafBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }


#    walva_haf.example:
#        class: %walva_haf.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
