<?php

namespace Walva\VideoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbstractVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractVideoRepository extends EntityRepository
{
}
