<?php

namespace Walva\VideoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InternalVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternalVideoRepository extends EntityRepository
{
}
