<?php

namespace HAF\CalendarBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryDescriptionRepository extends EntityRepository
{
}
