parameters:
#    walva_video.example.class: Walva\VideoBundle\Example

services:
#    walva_video.example:
#        class: %walva_video.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
