<?php

namespace Walva\HafBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends EntityRepository
{

    public function findByLanguagePagined($locale = "fr", $page = 1, $itemPerPage = 10)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select("livre")
            ->from("WalvaHafBundle:Livre", "livre")
            ->where("livre.langue = :language")
            ->orderBy("livre.dateCreation", "DESC")
            ->setFirstResult(($page -1) * $itemPerPage)
            ->setMaxResults($itemPerPage)
            ->setParameter("language", $locale)
            ->getQuery();

        return new Paginator($query);
    }


}
