<?php

namespace Walva\HafBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpotlightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpotlightRepository extends EntityRepository
{

    public function getSpotlightedEntities($locale)
    {

//        $queryBuilder
//            ->select("article")
//            ->from('WalvaHafBundle:Spotlight', 'spotlight')
//            ->join('spotlight.article', 'article')
//            ->where('spotlight.until > :date')
//            ->andWhere('article.langue = :locale')
//            ->setParameter('locale', $locale)
//            ->setParameter('date', new \DateTime());

//
//        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
//        $queryBuilder
//            ->select("article")
////            ->from('WalvaHafBundle:Article', 'article')
//            ->from('WalvaHafBundle:Spotlight', 'spotlight')
//            ->join('spotlight.article', 'article')
//            ->where('spotlight.until > :date')
//            ->andWhere('article.langue = :locale')
//            ->groupBy('article.id')
//        ->setParameter('locale', $locale)
//        ->setParameter('date', new \DateTime());

//        return $queryBuilder->getQuery()->execute();

        $query = $this->getEntityManager()->createQuery('SELECT a
        FROM WalvaHafBundle:Article a
        JOIN WalvaHafBundle:Spotlight spotlight WITH a.id = spotlight.article
        WHERE spotlight.until > :now AND a.langue = :locale
        ORDER BY spotlight.until DESC
        ');

        $query->setParameter(':now', new \DateTime());
        $query->setParameter(':locale', $locale);

        return $query->execute();
    }

}
